import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import IndexList from '../components/elements/IndexList/IndexList'
import MainTitle from '../components/elements/MainTitle/MainTitle'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Over The Wire Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainTitle>Welcome to my Over The Wire Blog</MainTitle>

        <ul>
          <li>
            <Link href='/bandit'>Bandit</Link>
            <IndexList
              path='/bandit/'
              text='bandit'
              range={1}
            />
          </li>
          <li>
            Natas
            <IndexList
              path='/natas/'
              text='natas'
              range={6}
            />
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export default Home
