import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Over The Wire Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Over The Wire Blog
        </h1>

        <ul>
          <li>
            <Link href='/bandit'>Bandit</Link>
            <ol>
              <li><Link href='/bandit/level0'>level 0</Link></li>
              <li><Link href=''>level 1</Link></li>
              <li><Link href=''>level 2</Link></li>
            </ol>
          </li>
          <li>
            Natas
            <ol>
              <li><Link href=''>level 0</Link></li>
              <li><Link href=''>level 1</Link></li>
              <li><Link href=''>level 2</Link></li>
            </ol>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export default Home
